$axure.loadCurrentPage({
  "url":"9后台管理界面.html",
  "generationDate":new Date(1513783706883.82),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a201a60dc4b44790afbee1b61b8fe124",
    "type":"Axure:Page",
    "name":"9后台管理界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"48a9fde103a54eed8e708165e2d95fd0",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":10},
            "size":{
              "width":683,
              "height":446}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f52967307eab46798a27af01eea57a59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":10},
                "size":{
                  "width":683,
                  "height":446}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/9后台管理界面/u0.png"}},
{
          "id":"cbc14c20100a49598b698ff3c41df48d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":312,
              "y":31},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"103b613fe41045ae8a7cecd18d1a72b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":312,
                  "y":31},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88dd4e134bb54c1789a0f18f75c4ff19",
          "label":"退出u",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":314},
            "size":{
              "width":588,
              "height":38}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 8后台登录",
                      "target":{
                        "targetType":"page",
                        "url":"8后台登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"63bda91155e3493e8d61d0b5ea2211b7",
          "label":"跳转到后台订单处理",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":67},
            "size":{
              "width":588,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8d7d7075f794155a8486505927f22fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":67},
                "size":{
                  "width":588,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 10后台订单处理",
                      "target":{
                        "targetType":"page",
                        "url":"10后台订单处理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/9后台管理界面/跳转到后台订单处理_u5.png"}},
{
          "id":"10c54708d0cd438f944469eaa75b6c81",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":75},
            "size":{
              "width":173,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1dbee103058c4bfeac1dbf02b484dcfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":75},
                "size":{
                  "width":173,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"959f1d26e2f744c8966e496487ba1d07",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":103},
            "size":{
              "width":85,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60f441c359e04f4e94193763d4aba29d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":103},
                "size":{
                  "width":85,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e376d20c4d784e5faca39f5657cc7d50",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":143},
            "size":{
              "width":588,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36b630d5f4ce48f9a0c56977ab2e6c9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":143},
                "size":{
                  "width":588,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/9后台管理界面/跳转到后台订单处理_u5.png"}},
{
          "id":"178083d948e94e61b338886dff375da6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":150},
            "size":{
              "width":173,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96783f77226548788efe7c769dd40e2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":85,
                  "y":150},
                "size":{
                  "width":173,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ef732067f85466aa725dd861d2503bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":179},
            "size":{
              "width":85,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec437b95e2d74a7392d213f88abeab0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":85,
                  "y":179},
                "size":{
                  "width":85,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1380f112e4d94dc3ac6113413ed4a756",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":219},
            "size":{
              "width":588,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b869d57bf114313b2f91ba7a888b8c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":219},
                "size":{
                  "width":588,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/9后台管理界面/跳转到后台订单处理_u5.png"}},
{
          "id":"311e8c935a244de69f13cb4215617860",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":226},
            "size":{
              "width":173,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5592102543e46fea411f7c5413499d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":85,
                  "y":226},
                "size":{
                  "width":173,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d722c7f04e084671822b9b574bad1689",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":255},
            "size":{
              "width":85,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60730968c58d45f5b816c6227e78b0cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":85,
                  "y":255},
                "size":{
                  "width":85,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "48a9fde103a54eed8e708165e2d95fd0":{
      "scriptId":"u0"},
    "f52967307eab46798a27af01eea57a59":{
      "scriptId":"u1"},
    "cbc14c20100a49598b698ff3c41df48d":{
      "scriptId":"u2"},
    "103b613fe41045ae8a7cecd18d1a72b4":{
      "scriptId":"u3"},
    "88dd4e134bb54c1789a0f18f75c4ff19":{
      "scriptId":"u4"},
    "63bda91155e3493e8d61d0b5ea2211b7":{
      "scriptId":"u5"},
    "f8d7d7075f794155a8486505927f22fc":{
      "scriptId":"u6"},
    "10c54708d0cd438f944469eaa75b6c81":{
      "scriptId":"u7"},
    "1dbee103058c4bfeac1dbf02b484dcfa":{
      "scriptId":"u8"},
    "959f1d26e2f744c8966e496487ba1d07":{
      "scriptId":"u9"},
    "60f441c359e04f4e94193763d4aba29d":{
      "scriptId":"u10"},
    "e376d20c4d784e5faca39f5657cc7d50":{
      "scriptId":"u11"},
    "36b630d5f4ce48f9a0c56977ab2e6c9d":{
      "scriptId":"u12"},
    "178083d948e94e61b338886dff375da6":{
      "scriptId":"u13"},
    "96783f77226548788efe7c769dd40e2b":{
      "scriptId":"u14"},
    "0ef732067f85466aa725dd861d2503bc":{
      "scriptId":"u15"},
    "ec437b95e2d74a7392d213f88abeab0d":{
      "scriptId":"u16"},
    "1380f112e4d94dc3ac6113413ed4a756":{
      "scriptId":"u17"},
    "8b869d57bf114313b2f91ba7a888b8c4":{
      "scriptId":"u18"},
    "311e8c935a244de69f13cb4215617860":{
      "scriptId":"u19"},
    "e5592102543e46fea411f7c5413499d5":{
      "scriptId":"u20"},
    "d722c7f04e084671822b9b574bad1689":{
      "scriptId":"u21"},
    "60730968c58d45f5b816c6227e78b0cf":{
      "scriptId":"u22"}}});