$axure.loadCurrentPage({
  "url":"7订单详情.html",
  "generationDate":new Date(1513783706285.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7ef299a069fa45c7b643b5434b4f43ea",
    "type":"Axure:Page",
    "name":"7订单详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"94ab11971eef4608b137db52b288b19d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":280,
              "height":470}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6a20d224e094fa58c08230393a4ccf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":280,
                  "height":470}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1用户登录/u0.png"}},
{
          "id":"21963fac16de46aea3946aed5b06132e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":102,
              "y":32},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2861c23d0be64fb68711dce625b446b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":102,
                  "y":32},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cbf297d5dc5142f39b02164ea97828eb",
          "label":"返回上页",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":330},
            "size":{
              "width":241,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 2菜单",
                      "target":{
                        "targetType":"page",
                        "url":"2菜单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"110f1be3e1464bb2b2a516db302eb990",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":70},
            "size":{
              "width":241,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c32ee9160874a40ac81472fca9eed65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":29,
                  "y":70},
                "size":{
                  "width":241,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7订单详情/u5.png"}},
{
          "id":"4117a0770a534243ab74a50332d2dad2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":78},
            "size":{
              "width":173,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08d57c3e6b85417fb9e26d5e82a3079b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":37,
                  "y":78},
                "size":{
                  "width":173,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34e6904d01444f77a876114842cecbc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":108},
            "size":{
              "width":85,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3695df910799445e9f5acc69bbd2eb1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":37,
                  "y":108},
                "size":{
                  "width":85,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35c320a5b4ec46e6ba8848d28b4095cc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":170},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdfc02aa88444ce8970df21974bfa069",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":170},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7订单详情/u11.png"}},
{
          "id":"327b02c3ebdb427998e10fddaa949e50",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":114,
              "y":170},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2a9510a99874f3586320a085735ca52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":114,
                  "y":170},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7订单详情/u11.png"}},
{
          "id":"ad66ffebff0a40039ce7ba4201472b76",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":258},
            "size":{
              "width":85,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"869785b5a9fe4ca1af5a832cb41049e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":258},
                "size":{
                  "width":85,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e0d18317bd64a78b448ca19da2c7cd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h5",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":144},
            "size":{
              "width":68,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d60f488c18e46f4b9f3aa1d0d44a9ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":144},
                "size":{
                  "width":68,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "94ab11971eef4608b137db52b288b19d":{
      "scriptId":"u0"},
    "a6a20d224e094fa58c08230393a4ccf3":{
      "scriptId":"u1"},
    "21963fac16de46aea3946aed5b06132e":{
      "scriptId":"u2"},
    "2861c23d0be64fb68711dce625b446b8":{
      "scriptId":"u3"},
    "cbf297d5dc5142f39b02164ea97828eb":{
      "scriptId":"u4"},
    "110f1be3e1464bb2b2a516db302eb990":{
      "scriptId":"u5"},
    "8c32ee9160874a40ac81472fca9eed65":{
      "scriptId":"u6"},
    "4117a0770a534243ab74a50332d2dad2":{
      "scriptId":"u7"},
    "08d57c3e6b85417fb9e26d5e82a3079b":{
      "scriptId":"u8"},
    "34e6904d01444f77a876114842cecbc8":{
      "scriptId":"u9"},
    "3695df910799445e9f5acc69bbd2eb1d":{
      "scriptId":"u10"},
    "35c320a5b4ec46e6ba8848d28b4095cc":{
      "scriptId":"u11"},
    "fdfc02aa88444ce8970df21974bfa069":{
      "scriptId":"u12"},
    "327b02c3ebdb427998e10fddaa949e50":{
      "scriptId":"u13"},
    "e2a9510a99874f3586320a085735ca52":{
      "scriptId":"u14"},
    "ad66ffebff0a40039ce7ba4201472b76":{
      "scriptId":"u15"},
    "869785b5a9fe4ca1af5a832cb41049e3":{
      "scriptId":"u16"},
    "7e0d18317bd64a78b448ca19da2c7cd9":{
      "scriptId":"u17"},
    "1d60f488c18e46f4b9f3aa1d0d44a9ec":{
      "scriptId":"u18"}}});