$axure.loadCurrentPage({
  "url":"10后台订单处理.html",
  "generationDate":new Date(1513783707026.92),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"676e58bb332245a99585d4499429f559",
    "type":"Axure:Page",
    "name":"10后台订单处理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c1e2da6533234724a8dfd5d058c5951c",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":660,
              "height":470}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b65c10bfed3d47e595e180853152ddc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":660,
                  "height":470}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/8后台登录/u0.png"}},
{
          "id":"ec1ded003bfe4fe2a0fd60b04629748d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":302,
              "y":42},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf72811da2804846b04a6470f3193ad3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":302,
                  "y":42},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92bb23cb04e44cf49ba33496d904eb73",
          "label":"返回后台管理",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":340},
            "size":{
              "width":568,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 2菜单",
                      "target":{
                        "targetType":"page",
                        "url":"2菜单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"5400b7716d2445128ae300a28d601b28",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":80},
            "size":{
              "width":568,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9ca61605dcc4609b18ffc7ba76236d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":80},
                "size":{
                  "width":568,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/10后台订单处理/u5.png"}},
{
          "id":"d570434e1139455d9f89b780f05ce4ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":88},
            "size":{
              "width":173,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aab146a464034d52827c0123d8e7c522",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":84,
                  "y":88},
                "size":{
                  "width":173,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ab6d1baf98b4427ba0ed49f5af62d58",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":118},
            "size":{
              "width":85,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a2ca0bd56c544809900171ece611101",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":84,
                  "y":118},
                "size":{
                  "width":85,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d965d4751b67456ebd93082b7ee5f4dd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":91,
              "y":180},
            "size":{
              "width":52,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41796664f9494a50abb3f4dd294a6898",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":91,
                  "y":180},
                "size":{
                  "width":52,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/10后台订单处理/u11.png"}},
{
          "id":"4c116d16b88a441db75bb5bcc7aa6ae6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":180},
            "size":{
              "width":52,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42cbea242ad9494ea591863bf1c0d047",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":168,
                  "y":180},
                "size":{
                  "width":52,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/10后台订单处理/u11.png"}},
{
          "id":"4de0282829444ff0b7ad86a0130fa1cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":91,
              "y":268},
            "size":{
              "width":85,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"400ce8edcd9641878d6a1133b3515a3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":91,
                  "y":268},
                "size":{
                  "width":85,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de3118f700664495a25e62826f8f3d6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h5",
          "visible":true,
          "style":{
            "location":{
              "x":91,
              "y":154},
            "size":{
              "width":68,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc468801c11448088a4a721315191595",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":91,
                  "y":154},
                "size":{
                  "width":68,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "c1e2da6533234724a8dfd5d058c5951c":{
      "scriptId":"u0"},
    "b65c10bfed3d47e595e180853152ddc7":{
      "scriptId":"u1"},
    "ec1ded003bfe4fe2a0fd60b04629748d":{
      "scriptId":"u2"},
    "cf72811da2804846b04a6470f3193ad3":{
      "scriptId":"u3"},
    "92bb23cb04e44cf49ba33496d904eb73":{
      "scriptId":"u4"},
    "5400b7716d2445128ae300a28d601b28":{
      "scriptId":"u5"},
    "b9ca61605dcc4609b18ffc7ba76236d8":{
      "scriptId":"u6"},
    "d570434e1139455d9f89b780f05ce4ff":{
      "scriptId":"u7"},
    "aab146a464034d52827c0123d8e7c522":{
      "scriptId":"u8"},
    "1ab6d1baf98b4427ba0ed49f5af62d58":{
      "scriptId":"u9"},
    "0a2ca0bd56c544809900171ece611101":{
      "scriptId":"u10"},
    "d965d4751b67456ebd93082b7ee5f4dd":{
      "scriptId":"u11"},
    "41796664f9494a50abb3f4dd294a6898":{
      "scriptId":"u12"},
    "4c116d16b88a441db75bb5bcc7aa6ae6":{
      "scriptId":"u13"},
    "42cbea242ad9494ea591863bf1c0d047":{
      "scriptId":"u14"},
    "4de0282829444ff0b7ad86a0130fa1cc":{
      "scriptId":"u15"},
    "400ce8edcd9641878d6a1133b3515a3e":{
      "scriptId":"u16"},
    "de3118f700664495a25e62826f8f3d6e":{
      "scriptId":"u17"},
    "dc468801c11448088a4a721315191595":{
      "scriptId":"u18"}}});