$axure.loadCurrentPage({
  "url":"6订单管理.html",
  "generationDate":new Date(1513783706034.22),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"97bc748f86ff4ee99222bffc23d1f275",
    "type":"Axure:Page",
    "name":"6订单管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"94ab11971eef4608b137db52b288b19d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":280,
              "height":470}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6a20d224e094fa58c08230393a4ccf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":280,
                  "height":470}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1用户登录/u0.png"}},
{
          "id":"21963fac16de46aea3946aed5b06132e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":102,
              "y":32},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2861c23d0be64fb68711dce625b446b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":102,
                  "y":32},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cbf297d5dc5142f39b02164ea97828eb",
          "label":"返回上页",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":330},
            "size":{
              "width":241,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 2菜单",
                      "target":{
                        "targetType":"page",
                        "url":"2菜单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"110f1be3e1464bb2b2a516db302eb990",
          "label":"跳转到订单详情",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":70},
            "size":{
              "width":241,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c32ee9160874a40ac81472fca9eed65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":29,
                  "y":70},
                "size":{
                  "width":241,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 7订单详情",
                      "target":{
                        "targetType":"page",
                        "url":"7订单详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/6订单管理/跳转到订单详情_u5.png"}},
{
          "id":"4117a0770a534243ab74a50332d2dad2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":78},
            "size":{
              "width":173,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08d57c3e6b85417fb9e26d5e82a3079b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":37,
                  "y":78},
                "size":{
                  "width":173,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34e6904d01444f77a876114842cecbc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":108},
            "size":{
              "width":85,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3695df910799445e9f5acc69bbd2eb1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":37,
                  "y":108},
                "size":{
                  "width":85,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cfb45471e303494a8bdeb382d1141d25",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":150},
            "size":{
              "width":241,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd671566b6374661a3510173b7199f72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":150},
                "size":{
                  "width":241,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/6订单管理/跳转到订单详情_u5.png"}},
{
          "id":"ecafa1458f5d47c3a26e8ab38d312db1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":158},
            "size":{
              "width":173,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"242b930cb87f4caeb31d14cdaab2a29d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":158},
                "size":{
                  "width":173,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8bb257c2d12140d783e0210208c28d63",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":188},
            "size":{
              "width":85,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14f9194222a24c35b20f19cb61c82f44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":188},
                "size":{
                  "width":85,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d77c91b34284caabca9a981b993e332",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":230},
            "size":{
              "width":241,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7735567b0df64f38af8abf884a13807e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":230},
                "size":{
                  "width":241,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/6订单管理/跳转到订单详情_u5.png"}},
{
          "id":"ab63269e20ae45a2b4f0e117efd5abf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":238},
            "size":{
              "width":173,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f2cfd80a7ad4eb9b2b7cd4f041741b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":238},
                "size":{
                  "width":173,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e44db55b19ed4dcc8cbcb04f31ab961a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":268},
            "size":{
              "width":85,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ce212f764fe4ccd987319eb671bfc37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":268},
                "size":{
                  "width":85,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "94ab11971eef4608b137db52b288b19d":{
      "scriptId":"u0"},
    "a6a20d224e094fa58c08230393a4ccf3":{
      "scriptId":"u1"},
    "21963fac16de46aea3946aed5b06132e":{
      "scriptId":"u2"},
    "2861c23d0be64fb68711dce625b446b8":{
      "scriptId":"u3"},
    "cbf297d5dc5142f39b02164ea97828eb":{
      "scriptId":"u4"},
    "110f1be3e1464bb2b2a516db302eb990":{
      "scriptId":"u5"},
    "8c32ee9160874a40ac81472fca9eed65":{
      "scriptId":"u6"},
    "4117a0770a534243ab74a50332d2dad2":{
      "scriptId":"u7"},
    "08d57c3e6b85417fb9e26d5e82a3079b":{
      "scriptId":"u8"},
    "34e6904d01444f77a876114842cecbc8":{
      "scriptId":"u9"},
    "3695df910799445e9f5acc69bbd2eb1d":{
      "scriptId":"u10"},
    "cfb45471e303494a8bdeb382d1141d25":{
      "scriptId":"u11"},
    "dd671566b6374661a3510173b7199f72":{
      "scriptId":"u12"},
    "ecafa1458f5d47c3a26e8ab38d312db1":{
      "scriptId":"u13"},
    "242b930cb87f4caeb31d14cdaab2a29d":{
      "scriptId":"u14"},
    "8bb257c2d12140d783e0210208c28d63":{
      "scriptId":"u15"},
    "14f9194222a24c35b20f19cb61c82f44":{
      "scriptId":"u16"},
    "3d77c91b34284caabca9a981b993e332":{
      "scriptId":"u17"},
    "7735567b0df64f38af8abf884a13807e":{
      "scriptId":"u18"},
    "ab63269e20ae45a2b4f0e117efd5abf8":{
      "scriptId":"u19"},
    "1f2cfd80a7ad4eb9b2b7cd4f041741b9":{
      "scriptId":"u20"},
    "e44db55b19ed4dcc8cbcb04f31ab961a":{
      "scriptId":"u21"},
    "6ce212f764fe4ccd987319eb671bfc37":{
      "scriptId":"u22"}}});