$axure.loadCurrentPage({
  "url":"5商品维修.html",
  "generationDate":new Date(1513783705867.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c2938414821a4b30a4f2a5bb05b7652c",
    "type":"Axure:Page",
    "name":"5商品维修",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"94ab11971eef4608b137db52b288b19d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":280,
              "height":470}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6a20d224e094fa58c08230393a4ccf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":280,
                  "height":470}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1用户登录/u0.png"}},
{
          "id":"21963fac16de46aea3946aed5b06132e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":102,
              "y":32},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2861c23d0be64fb68711dce625b446b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":102,
                  "y":32},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dacdd214f7db4ec391e8c6f62dd1423a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":72},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34f7e2967c3641879170ffe19367cf3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":72},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a2335b7b10994dabbd9a1bd6a090118f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":114,
              "y":140},
            "size":{
              "width":75,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8c567a3e3fca4c43b9bbe51726a03ba7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":70},
            "size":{
              "width":157,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"527cef94ccfe4ebf8661e2ac1517da30",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":107},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9909d28e4116470687c677e04ed56e48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":107},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4deffe6cdfd46948ae951c759f2da4e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":114,
              "y":105},
            "size":{
              "width":157,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9a108671830f4da8b647ea4ca3ac3110",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":187},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8b11234ab6c4e7ab3b4b494b3f65818",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":29,
                  "y":187},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2990b61d0ccb4bc1b42b26a6c2598681",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":185},
            "size":{
              "width":157,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0fddca9928b848358c5927ed8b89547b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":222},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60ad22fd876f458d95bec3886e46a43e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":29,
                  "y":222},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8315be00b1da4397bf056d1f1ba500e8",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":220},
            "size":{
              "width":157,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4d35379689104172b529dd00236b03f4",
          "label":"跳转到订单详情页面",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":270},
            "size":{
              "width":110,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 2菜单",
                      "target":{
                        "targetType":"page",
                        "url":"2菜单.html",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 7订单详情",
                      "target":{
                        "targetType":"page",
                        "url":"7订单详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"89ea7d4bbb4148fcba0ef18e29bfd32b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h5",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":333},
            "size":{
              "width":126,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"126a56bd427646ca9ecf39ab31bae2af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":29,
                  "y":333},
                "size":{
                  "width":126,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cbf297d5dc5142f39b02164ea97828eb",
          "label":"返回菜单",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":270},
            "size":{
              "width":110,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 2菜单",
                      "target":{
                        "targetType":"page",
                        "url":"2菜单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "94ab11971eef4608b137db52b288b19d":{
      "scriptId":"u0"},
    "a6a20d224e094fa58c08230393a4ccf3":{
      "scriptId":"u1"},
    "21963fac16de46aea3946aed5b06132e":{
      "scriptId":"u2"},
    "2861c23d0be64fb68711dce625b446b8":{
      "scriptId":"u3"},
    "dacdd214f7db4ec391e8c6f62dd1423a":{
      "scriptId":"u4"},
    "34f7e2967c3641879170ffe19367cf3d":{
      "scriptId":"u5"},
    "a2335b7b10994dabbd9a1bd6a090118f":{
      "scriptId":"u6"},
    "8c567a3e3fca4c43b9bbe51726a03ba7":{
      "scriptId":"u7"},
    "527cef94ccfe4ebf8661e2ac1517da30":{
      "scriptId":"u8"},
    "9909d28e4116470687c677e04ed56e48":{
      "scriptId":"u9"},
    "c4deffe6cdfd46948ae951c759f2da4e":{
      "scriptId":"u10"},
    "9a108671830f4da8b647ea4ca3ac3110":{
      "scriptId":"u11"},
    "a8b11234ab6c4e7ab3b4b494b3f65818":{
      "scriptId":"u12"},
    "2990b61d0ccb4bc1b42b26a6c2598681":{
      "scriptId":"u13"},
    "0fddca9928b848358c5927ed8b89547b":{
      "scriptId":"u14"},
    "60ad22fd876f458d95bec3886e46a43e":{
      "scriptId":"u15"},
    "8315be00b1da4397bf056d1f1ba500e8":{
      "scriptId":"u16"},
    "4d35379689104172b529dd00236b03f4":{
      "scriptId":"u17"},
    "89ea7d4bbb4148fcba0ef18e29bfd32b":{
      "scriptId":"u18"},
    "126a56bd427646ca9ecf39ab31bae2af":{
      "scriptId":"u19"},
    "cbf297d5dc5142f39b02164ea97828eb":{
      "scriptId":"u20"}}});